<?php

namespace AppBundle\Repository;

/**
 * FichePvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichePvRepository extends \Doctrine\ORM\EntityRepository
{
}
